force-app/main/default/objects/SubToDo__c/SubToDo__c.object-meta.xml
<CustomObject>
    <label>SubToDo</label>
    <nameField>
        <label>SubToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>SubToDos</relationshipLabel>
    <relationshipName>SubToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/recordTypes/Development.recordType-meta.xml
<RecordType>
    <fullName>Development</fullName>
    <active>true</active>
    <label>Development</label>
</RecordType>

src/classes/CaseTriggerHelperTest.cls
/**
 * Created by vladimirzhukovets on 21.09.21.
 */

@IsTest
private class CaseTriggerHelperTest {
    @IsTest(SeeAllData=true)
    static void addToDoFromEmailTest() {
        List<Case> cases = new List<Case>();
        Case caseObj = TestDataFactory.CASEOBJ.createDummyCase('Test todo, dEVelopment', 'Test subtodo', 'Email', '0055g00000CxaO8AAJ', true);
        ToDo__c expectedTodo = TestDataFactory.TODO.createDummyTodo('Test todo', '0125g000001qnSTAAY','0055g00000CxaO8AAJ', false);
        SubToDo__c expectedSubTodo = TestDataFactory.SUBTODO.createDummySubTodo('Test subtodo', false);
        cases.add(caseObj);

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ToDoTriggerHandlerHelper());
        caseObj.Subject = 'Test todo, dEVelopment';
        update caseObj;
        CaseTriggerHelper.addToDoFromEmail(cases);
        Test.stopTest();

        ToDo__c actualTodo = [SELECT Id, Name, RecordTypeId, OwnerId FROM ToDo__c WHERE Name LIKE '%Test todo%' LIMIT 1];
        SubToDo__c actualSubTodo = [SELECT Name, Todo__c FROM SubToDo__c WHERE Name LIKE '%Test subtodo%' LIMIT 1];
        System.assertEquals(expectedTodo.Name, actualTodo.Name);
        System.assertEquals(expectedTodo.RecordTypeId, actualTodo.RecordTypeId);
        System.assertEquals(expectedTodo.OwnerId, actualTodo.OwnerId);
        System.assertEquals(expectedSubTodo.Name, actualSubTodo.Name);
        System.assertEquals(actualTodo.Id, actualSubTodo.ToDo__c);
    }
}