force-app/main/default/objects/SubToDo__c/SubToDo__c.object-meta.xml
<CustomObject>
    <label>SubToDo</label>
    <nameField>
        <label>SubToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SubTodoHttpMock.cls
@isTest
global class SubTodoHttpMock implements HttpCalloutMock {
    global HTTPResponse respond(HTTPRequest req) {
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-type', 'application/json;charset=UTF-8');
        
        Map<Id, SubToDo__c> subtodoMap = new Map<Id, SubToDo__c>([SELECT Id FROM SubToDo__c]);
        for(SubToDo__c subtodo : subtodoMap.values()){
            subtodo.Connected_Org_Record_Id__c = subtodo.Id;
        }
        res.setBody(JSON.serialize(subtodoMap.values()));
        res.setStatusCode(200);
        return res;
    }
}