force-app/main/default/objects/SubToDo__c/SubToDo__c.object-meta.xml
<CustomObject>
    <label>SubToDo</label>
    <nameField>
        <label>SubToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SubToDo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priorities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>SubToDos</relationshipLabel>
    <relationshipName>SubToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priorities</valueSetName>
    </valueSet>
</CustomField>

src/classes/SubToDoHandler.cls
public with sharing class SubToDoHandler {

    @AuraEnabled(cacheable=true)
    public static List<SubToDo__c> getSubToDosOfTodo(Id todoId) {
        return [
                SELECT Name, Description__c, Priority__c, Connected_Org_Record_Id__c,
                        Image_URL__c, Is_Done__c, CreatedDate, ToDo__c, LastModifiedById
                FROM SubToDo__c
                WHERE ToDo__c =: todoId
        ];
    }
}