force-app/main/default/objects/SubToDo__c/SubToDo__c.object-meta.xml
<CustomObject>
    <label>SubToDo</label>
    <nameField>
        <label>SubToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>SubToDos</relationshipLabel>
    <relationshipName>SubToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SubToDoTriggerTest.cls
@IsTest
public with sharing class SubToDoTriggerTest {

    @isTest
    public static void testAfterInsertFuture(){
        
        //селектнуть существующую тудуху
        ToDo__c todo = new ToDo__c(Name='testTodo');
        insert todo;

        SubToDo__c[] subtodos = new List<SubToDo__c>();
        for(Integer i = 0; i < 5; i++){
            subtodos.add(
                new SubToDo__c(Name = 'SubTodo' + i, ToDo__c = todo.Id)
            );
        }
        insert subtodos;
        Map<Id, SubToDo__c> subtodoMap = new Map<Id, SubToDo__c>([SELECT Id FROM SubToDo__c]);
        Test.setMock(HttpCalloutMock.class, new SubTodoHttpMock());
        Test.startTest();
        SubToDoTriggerHandlerHelper.handleAfterInsert_future(subtodoMap.keySet());
        Test.stopTest();
        SubToDo__c[] newSubTodos = [SELECT Id, Connected_Org_Record_Id__c FROM SubToDo__c];
        for(SubToDo__c subtodo : newSubTodos){
            System.assertEquals(subtodo.Id, subtodo.Connected_Org_Record_Id__c);
        }
    }

    @isTest
    public static void testAfterUpdateFuture(){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('SubtodosResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        SubToDoTriggerHandlerHelper.handleAfterUpdate_future(new Set<Id>());
        Test.stopTest();
    }
    @isTest
    public static void testBeforeDeleteFuture(){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('SubtodosResource');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        SubToDoTriggerHandlerHelper.handleBeforeDelete_future(new Set<Id>());
        Test.stopTest();
    }
}