force-app/main/default/objects/SubToDo__c/SubToDo__c.object-meta.xml
<CustomObject>
    <label>SubToDo</label>
    <nameField>
        <label>SubToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>SubToDos</relationshipLabel>
    <relationshipName>SubToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SubToDoHandlerTest.cls
@IsTest
public class SubToDoHandlerTest {
	
    @IsTest(SeeAllData=false)
    public static void getSubtodosOfTodosTest(){
        
        ToDo__c expectedTodo1 = TestDataFactory.TODO.createDummyTodo('Test todo1', '0125g000001qnSTAAY','0055g00000CxaO8AAJ', true);
        ToDo__c expectedTodo2 = TestDataFactory.TODO.createDummyTodo('Test todo2', '0125g000001qnSTAAY','0055g00000CxaO8AAJ', true);
        SubToDo__c expectedSubTodo1 = TestDataFactory.SUBTODO.createDummySubTodo('Test subtodo1', false);
        SubToDo__c expectedSubTodo2 = TestDataFactory.SUBTODO.createDummySubTodo('Test subtodo2', false);
        expectedSubTodo1.ToDo__c = expectedTodo1.id;
        expectedSubTodo2.ToDo__c = expectedTodo1.id;
        insert expectedSubTodo1;
        insert expectedSubTodo2;
		 
        String aimTodo = [SELECT Id, Name FROM ToDo__c WHERE Name =: 'Test todo1'].get(0).id;
        Test.startTest();
        List<SubToDo__c> subs = SubToDoHandler.getSubToDosOfTodo(aimTodo);
        Test.stopTest();
        System.assertEquals(2, subs.size());
        System.assertEquals(0, subs.size());
        
    }
    
    
    
    
}