force-app/main/default/objects/SubToDo__c/SubToDo__c.object-meta.xml
<CustomObject>
    <label>SubToDo</label>
    <nameField>
        <label>SubToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubToDos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SubToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SubToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SubToDo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priorities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SubToDo__c/fields/ToDo__c.field-meta.xml
<CustomField>
    <fullName>ToDo__c</fullName>
    <label>ToDo</label>
    <referenceTo>ToDo__c</referenceTo>
    <relationshipLabel>SubToDos</relationshipLabel>
    <relationshipName>SubToDos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priorities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubToDoTriggerHandlerHelper.cls
public with sharing class SubToDoTriggerHandlerHelper {
    
     /*public static Map<Id, ToDo__c> getMapOfSubtodosTodos(List<SubToDo__c> subtodos){
        List<Id> todoIds = new List<Id>();
        for(SubToDo__C sub : subtodos){
            todoIds.add(sub.ToDo__c);
        }
        //select todos which have subtodos from request
        List<ToDo__c> todosOfSubtodos = 
            new List<ToDo__c>([select id, Connected_Org_Record_Id__c from ToDo__c where Connected_Org_Record_Id__c in: todoIds]);
        
        Map<Id, ToDo__c> mapTodos = new Map<Id, ToDo__c>();
       	for(ToDo__c tod : todosOfSubtodos){
               mapTodos.put(tod.Connected_Org_Record_Id__c, tod);
        }
        return mapTodos;
    }*/
    

    @future(callout=true)
    public static void handleAfterInsert_future(Set<Id> ids){
        Map<Id, SubToDo__c> subtodosMap = new Map<Id, SubToDo__c>([
                SELECT Name, Description__c, Is_Done__c, Priority__c,
                        Image_URL__c, Connected_Org_Record_Id__c, ToDo__c
                FROM SubToDo__c
                WHERE Id IN :ids
        ]);
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:devorg_2_credential/services/apexrest/subtodoapi/');
        req.setMethod('POST');
        req.setHeader('Content-type', 'application/json;charset=UTF-8');
        req.setBody(JSON.serialize(subtodosMap.values()));
        Http http = new Http();
        HttpResponse resp = http.send(req);
        List<SubToDo__c> syncedSubtodos =
                (List<SubToDo__c>) JSON.deserialize(resp.getBody(), List<SubToDo__c>.class);
        for (SubToDo__c subtodo : syncedSubtodos) {
            subtodosMap.get(subtodo.Connected_Org_Record_Id__c).
            Connected_Org_Record_Id__c = subtodo.Id;
        }
        update subtodosMap.values();
    }
     
    @future(callout = true)
    public static void handleAfterUpdate_future(Set<Id> ids) {
        List<SubToDo__c> subtodos = [
                SELECT Name, Description__c, Is_Done__c, Priority__c,
                        Image_URL__c, Connected_Org_Record_Id__c, ToDo__c
                FROM SubToDo__c
                WHERE Id IN :ids
        ];
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:devorg_2_credential/services/apexrest/subtodoapi/');
        req.setMethod('PATCH');
        req.setHeader('Content-type', 'application/json;charset=UTF-8');
        req.setBody(JSON.serialize(subtodos));
        Http http = new Http();
        HttpResponse resp = http.send(req);
    }
    
	@future(callout = true)
    public static void handleBeforeDelete_future(Set<Id> ids) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:devorg_2_credential/services/apexrest/subtodoapi/');
        req.setMethod('DELETE');
        req.setHeader('Content-type', 'application/json;charset=UTF-8');
        req.setBody(JSON.serialize(ids));
        Http http = new Http();
        HttpResponse resp = http.send(req);
    }    
	    
}