force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Is_Done__c.field-meta.xml
<CustomField>
    <fullName>Is_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ToDo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priorities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Administration.recordType-meta.xml
<RecordType>
    <fullName>Administration</fullName>
    <active>true</active>
    <label>Administration</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Development.recordType-meta.xml
<RecordType>
    <fullName>Development</fullName>
    <active>true</active>
    <label>Development</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Management.recordType-meta.xml
<RecordType>
    <fullName>Management</fullName>
    <active>true</active>
    <label>Management</label>
</RecordType>

force-app/main/default/classes/ToDoTriggerHandlerHelper.cls
public with sharing class ToDoTriggerHandlerHelper {
        public static void handleBeforeUpdate(){
                for(ToDo__c todo : (List<ToDo__c>)Trigger.new){
                        todo.Connected_Org_Record_Id__c = 
                        ((Map<Id, ToDo__C>)Trigger.oldMap).get(todo.Id).Connected_Org_Record_Id__c;
                }
        }
    
   		public static void setAfterInsertQueueByRecordType(Set<Id> ids){
        	List<ToDo__c> todos = new List<ToDo__c>([
                SELECT Name, Description__c, Is_Done__c, Priority__c,
                        Image_URL__c, Connected_Org_Record_Id__c, RecordTypeId
                FROM ToDo__c
                WHERE Id IN :ids]);
            
            Map<String, Id> recTypeIds = new Map<String, Id>();
            recTypeIds.put('Management', Schema.SObjectType.ToDo__c.getRecordTypeInfosByName().get('Management').getRecordTypeId());
            recTypeIds.put('Administration', Schema.SObjectType.ToDo__c.getRecordTypeInfosByName().get('Administration').getRecordTypeId());
            recTypeIds.put('Development', Schema.SObjectType.ToDo__c.getRecordTypeInfosByName().get('Development').getRecordTypeId());
            //Да, да, трожки говнокод, но пока хз, как это норм и удобно в коллекции оформить да и онли 6 запросов идет в бдху на транзакцию ОТСЮДАВА
            Group qMan = [SELECT Id FROM Group WHERE Name = 'Managequeue' and Type='Queue'];
            Group qDev = [SELECT Id FROM Group WHERE Name = 'Devqueue' and Type='Queue'];
            Group qAdm = [SELECT Id FROM Group WHERE Name = 'Adminqueue' and Type='Queue'];
            for(ToDo__c todo : todos){
                if(todo.RecordTypeId == recTypeIds.get('Management')){
                    todo.OwnerId = qMan.id; 
                }
                if(todo.RecordTypeId == recTypeIds.get('Development')){
                    todo.OwnerId = qDev.id;
                }
                if(todo.RecordTypeId == recTypeIds.get('Administration')){
                    todo.OwnerId = qAdm.id;
                }
            }
            update todos;
          
    	}
    
    
        @future(callout = true)
        public static void handleAfterInsert_future(Set<Id> ids) {
        Map<Id, ToDo__c> todosMap = new Map<Id, ToDo__c>([
                SELECT Name, Description__c, Is_Done__c, Priority__c,
                        Image_URL__c, Connected_Org_Record_Id__c, RecordType.Name
                FROM ToDo__c
                WHERE Id IN :ids
        ]);
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:devorg_2_credential/services/apexrest/todoapi/');
        req.setMethod('POST');
        req.setHeader('Content-type', 'application/json;charset=UTF-8');
        req.setBody(JSON.serialize(todosMap.values()));
        Http http = new Http();
        HttpResponse resp = http.send(req);
        List<ToDo__c> syncedTodos =
                (List<ToDo__c>) JSON.deserialize(resp.getBody(), List<ToDo__c>.class);
        for (ToDo__c todo : syncedTodos) {
            todosMap.get(todo.Connected_Org_Record_Id__c).
                    Connected_Org_Record_Id__c = todo.Id;
        }
        update todosMap.values();
    }
    @future(callout = true)
    public static void handleAfterUpdate_future(Set<Id> ids) {
        List<ToDo__c> todos = [
                SELECT Name, Description__c, Is_Done__c, Priority__c,
                        Image_URL__c, Connected_Org_Record_Id__c
                FROM ToDo__c
                WHERE Id IN :ids
        ];
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:devorg_2_credential/services/apexrest/todoapi/');
        req.setMethod('PATCH');
        req.setHeader('Content-type', 'application/json;charset=UTF-8');
        req.setBody(JSON.serialize(todos));
        Http http = new Http();
        HttpResponse resp = http.send(req);
    }
    @future(callout = true)
    public static void handleBeforeDelete_future(Set<Id> ids) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:devorg_2_credential/services/apexrest/todoapi/');
        req.setMethod('DELETE');
        req.setHeader('Content-type', 'application/json;charset=UTF-8');
        req.setBody(JSON.serialize(ids));
        Http http = new Http();
        HttpResponse resp = http.send(req);
    }
}