force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Connected_Org_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Connected_Org_Record_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Connected Org Record Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/tests/TodoHttpMock.cls
@isTest
global class TodoHttpMock implements HttpCalloutMock {
    global HTTPResponse respond(HTTPRequest req) {
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-type', 'application/json;charset=UTF-8');
        Map<Id, ToDo__c> todoMap = new Map<Id, ToDo__c>([SELECT Id FROM ToDo__c]);
        for(ToDo__c todo : todoMap.values()){
            todo.Connected_Org_Record_Id__c = todo.Id;
        }
        res.setBody(JSON.serialize(todoMap.values()));
        res.setStatusCode(200);
        return res;
    }
}