force-app/main/default/objects/ToDo__c/ToDo__c.object-meta.xml
<CustomObject>
    <label>ToDo</label>
    <nameField>
        <label>ToDo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ToDos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ToDo__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Priorities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ToDo__c/recordTypes/Administration.recordType-meta.xml
<RecordType>
    <fullName>Administration</fullName>
    <active>true</active>
    <label>Administration</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Development.recordType-meta.xml
<RecordType>
    <fullName>Development</fullName>
    <active>true</active>
    <label>Development</label>
</RecordType>

force-app/main/default/objects/ToDo__c/recordTypes/Management.recordType-meta.xml
<RecordType>
    <fullName>Management</fullName>
    <active>true</active>
    <label>Management</label>
</RecordType>

force-app/main/default/classes/CaseTriggerHelper.cls
public class CaseTriggerHelper {
    public static void addToDoFromEmail(List<Case> newCases){
        Map<Id, ToDo__c> cIdTodoMap = new Map<Id, ToDo__c>();
        for(Case newCase : newCases){
            String priority = newCase.Description;
            if(newCase.Origin == 'Email') {
                List<String> recordTypesFromSubject = newCase.Subject.split(',');
                if (recordTypesFromSubject.size() > 1){
                    String recordType = recordTypesFromSubject.get(1).trim().toLowerCase();
                    switch on recordType{
                        when 'development'{
                            cIdTodoMap.put(newCase.Id, 
                			new ToDo__c(Name = recordTypesFromSubject.get(0), OwnerId = newCase.OwnerId, RecordTypeId = '0125g000001qnSTAAY', Priority__c = priority));
                        }
                        when 'administration'{
                            cIdTodoMap.put(newCase.Id, 
                			new ToDo__c(Name = recordTypesFromSubject.get(0), OwnerId = newCase.OwnerId, RecordTypeId = '0125g000001qnSYAAY', Priority__c = priority));
                        }
                        when 'management'{
                            cIdTodoMap.put(newCase.Id, 
                			new ToDo__c(Name = recordTypesFromSubject.get(0), OwnerId = newCase.OwnerId, RecordTypeId = '0125g000001qnSdAAI', Priority__c = priority));
                        }
                        when else{
                            cIdTodoMap.put(newCase.Id, 
                			new ToDo__c(Name = newCase.Subject, OwnerId = newCase.OwnerId, RecordTypeId = '0125g000001qnSdAAI', Priority__c = priority));
                        }
                    }
                } else {
                    cIdTodoMap.put(newCase.Id, 
                	new ToDo__c(Name = newCase.Subject, OwnerId = newCase.OwnerId, RecordTypeId = '0125g000001qnSdAAI', Priority__c = priority));
                }
            }
        }
        insert cIdTodoMap.values();
    }
}